name: holopop
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  provider: ^6.0.5
  http: ^1.1.0
  carousel_slider: ^4.2.1
  word_generator: ^0.4.3
  intl: ^0.19.0
  settings_ui: ^2.0.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3
  pointycastle: ^3.7.3
  video_player: ^2.8.1
  lottie: ^2.7.0
  dots_indicator: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  global_configuration: ^2.0.0
  flutter_linkify: ^6.0.0
  image_picker: ^1.0.7
  url_launcher: ^6.2.4
  flutter_svg: ^2.0.9
  toastification: ^1.2.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  logging: ^1.2.0
  awesome_notifications: ^0.9.2
  google_sign_in: ^6.1.6
  firebase_auth: ^4.16.0
  confetti: ^0.7.0
  qr_flutter: ^4.1.0
  linkify: ^5.0.0
  mailto: ^2.0.0
  mobile_scanner: ^4.0.1
  flutter_native_contact_picker: ^0.0.6
  chewie: ^1.7.5
  file_picker: ^6.1.1
  http_interceptor: ^2.0.0-beta.8
  collection: ^1.18.0
  flutter_downloader: ^1.11.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/holopop-app-icon.png"
  mind_sdk_android: 22

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/

    - configs/